In [57]:
#1. Створіть одновимірний масив (вектор)
#з першими 20-ма натуральними числами та виведіть його значення.

import numpy as np


mass = np.arange(0,20)
print("Вектор:", mass)

Вектор: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [58]:
#2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його 
#випадковими натуральними числами та виведіть його значення.
# под вопросом


mass2 = np.random.randint(0, 51, size=(3, 3))
print("Матриця: ")
print(mass2)

Матриця: 
[[28  8  0]
 [ 7  2 21]
 [27 28 27]]


In [59]:
#3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
#діапазоні від -10 до 10 та виведіть його значення.
# под вопросом

mass3 = np.random.randint(-10, 11, size=(5, 5))
print("Матриця:")
print(mass3)

Матриця:
[[  5   5  -6   9  10]
 [  8  -5   1   1   5]
 [ -7 -10  -3  -6  -9]
 [  9   3   0  -9   7]
 [ 10  -3  -3   6   0]]


In [60]:
#4. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами
#в діапазоні від 0 до 1 та знайдіть середнє значення елементів.

mass4 = np.random.rand(5,5)
print("Масив:")
print(mass4)
average_value = np.mean(mass4)
print("    ")
print("Середнє значення:", average_value)

Масив:
[[0.69532043 0.90386388 0.27435299 0.25891333 0.09247266]
 [0.17387953 0.69473756 0.78771095 0.07460266 0.54899061]
 [0.81104059 0.59838049 0.60466873 0.88577745 0.97158766]
 [0.54177342 0.05326764 0.25705355 0.84508422 0.37853528]
 [0.52298003 0.63061457 0.00097648 0.86898073 0.03433518]]
    
Середнє значення: 0.5003960241561086


In [61]:
#5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами
#в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

mass5 = np.random.randint(-10, 11, size=(5, 5))
mass6 = np.random.randint(-10, 11, size=(5, 5))

print("Перший масив:")
print(mass5)
print("    ")
print("Другий масив:")
print(mass6)
print("    ")
print("Додавання:")
print(mass5 + mass6)
print("    ")
print("Віднімання:")
print(mass5 - mass6)
print("    ")
print("Множення:")
print(mass5 * mass6)

Перший масив:
[[ 7  5 -4  7 -5]
 [ 8  2  6 -8 -3]
 [-2  4 -2  3  5]
 [ 1 -4  8  2  9]
 [ 3  9 -7 -9  6]]
    
Другий масив:
[[ 2  3  8 -7 -3]
 [ 8 -7  6  3  0]
 [ 6 -2 -9  5  1]
 [ 7 -6 10 -7  5]
 [ 4  7 -5 -9 -6]]
    
Додавання:
[[  9   8   4   0  -8]
 [ 16  -5  12  -5  -3]
 [  4   2 -11   8   6]
 [  8 -10  18  -5  14]
 [  7  16 -12 -18   0]]
    
Віднімання:
[[  5   2 -12  14  -2]
 [  0   9   0 -11  -3]
 [ -8   6   7  -2   4]
 [ -6   2  -2   9   4]
 [ -1   2  -2   0  12]]
    
Множення:
[[ 14  15 -32 -49  15]
 [ 64 -14  36 -24   0]
 [-12  -8  18  15   5]
 [  7  24  80 -14  45]
 [ 12  63  35  81 -36]]


In [62]:
#6. Створіть два вектори розміром 6, заповніть їх довільними дійсними
#числами та знайдіть їх скалярний добуток.

vector1 = np.array([1.1, 4.3, 6.5, 2.8, 2.2, 8.5])
vector2 = np.array([2.8, 1.2, 3.1, 7.3, 3.4, 1.7])

print("Перший вектор:")
print(vector1)
print("    ")
print("Другий вектор:")
print(vector2)

scalar_product = np.dot(vector1, vector2)
print("    ")
print("Скалярний добуток:", scalar_product)

Перший вектор:
[1.1 4.3 6.5 2.8 2.2 8.5]
    
Другий вектор:
[2.8 1.2 3.1 7.3 3.4 1.7]
    
Скалярний добуток: 70.76


In [63]:
#7. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами в
#діапазоні від 1 до 15 та перемножте їх між собою.

mass7 = np.random.randint(0, 16, size=(2, 3))
mass8 = np.random.randint(0, 16, size=(3, 2))
mass9 = mass8.reshape((2,3))

print("Перша матриця:")
print(mass7)
print ("   ")
print("Друга матриця:")
print(mass9)
print ("  ")
print("Множення:")
print (mass7 * mass9)

Перша матриця:
[[14 14  8]
 [ 8  8 15]]
   
Друга матриця:
[[ 4 13  2]
 [ 2  5  4]]
  
Множення:
[[ 56 182  16]
 [ 16  40  60]]


In [64]:
#8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
#від 1 до 12 та знайдіть її обернену матрицю.

mass10 = np.random.randint(0, 13, size=(3, 3))


print("Матриця: ")
print(mass10)
print ("  ")

inv_matrix = np.linalg.inv(mass10)
print("Інвертована матриця: ")
print(inv_matrix)

Матриця: 
[[ 4  5 12]
 [ 0  0  9]
 [ 3 11 12]]
  
Інвертована матриця: 
[[ 0.37931034 -0.27586207 -0.17241379]
 [-0.10344828 -0.04597701  0.13793103]
 [ 0.          0.11111111  0.        ]]


In [65]:
#9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні
#від -8 до 8 та транспонуйте її.

mass11 = np.random.randint(-8, 9, size=(4, 4))
print("Матриця: ")
print(mass11)
print("  ")

transp = mass11.T
print("Транспонована матриця: ")
print(transp)

Матриця: 
[[ 8 -4  7  4]
 [ 5 -5 -5  3]
 [ 2 -8 -5  2]
 [-4 -5  0  6]]
  
Транспонована матриця: 
[[ 8  5  2 -4]
 [-4 -5 -8 -5]
 [ 7 -5 -5  0]
 [ 4  3  2  6]]


In [66]:
#10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами
#в діапазоні від 1 до 10 та знайдіть середнє значення елементів матриці.

mass12 = np.random.randint(1, 11, size=(3, 4))
vector3 = np.random.randint(1, 11, size=4)

print("Матриця: ")
print(mass12)
print ("  ")
print("Вектор: ")
print(vector3)
print ("  ")

print("Середнє значення: ", mass12.mean())

Матриця: 
[[2 2 4 6]
 [9 1 9 8]
 [8 7 4 4]]
  
Вектор: 
[ 9  7  7 10]
  
Середнє значення:  5.333333333333333


In [67]:
#11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими
#числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1,
#і знайдіть добуток вектора на матрицю.

mass13 = np.random.randint(1, 11, size=(2, 3))
vector4 = np.random.random(3)

print("Матриця: ")
print(mass13)
print ("  ")
print("Вектор: ")
print(vector4)
print("  ")
print("Добуток вектора на матрицю: ")
result = np.dot(mass13, vector4)
print(result)

Матриця: 
[[1 9 3]
 [2 4 9]]
  
Вектор: 
[0.800533   0.37499005 0.66076567]
  
Добуток вектора на матрицю: 
[6.1577405  9.04791725]


In [68]:
#12.	Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами 
#діапазоні від 1 до 10 та знайдіть їхню різницю.

mass14 = np.random.randint(1, 11, size=(3, 3))
mass15 = np.random.randint(1, 11, size=(3, 3))

print("Перша Матриця: ")
print(mass14)
print ("  ")
print("Друга Матриця: ")
print(mass15)
print ("  ")
print("Різниця матриць: ")
print(mass14 - mass15)

Перша Матриця: 
[[6 8 9]
 [1 5 4]
 [5 7 4]]
  
Друга Матриця: 
[[10 10  3]
 [ 7  5  9]
 [ 9  1  1]]
  
Різниця матриць: 
[[-4 -2  6]
 [-6  0 -5]
 [-4  6  3]]


In [69]:
#13. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
#діапазоні від -5 до 5 та знайдіть їх добуток.

mass16 = np.random.randint(-5, 6, size=(3, 3))
mass17 = np.random.randint(-5, 6, size=(3, 3))


print("Перша Матриця: ")
print(mass16)
print ("  ")
print("Друга Матриця: ")
print(mass17)
print ("  ")
print("Добуток Матриць: ")
print(mass16 * mass17)

Перша Матриця: 
[[ 0 -5 -3]
 [ 2  2  0]
 [-2  4 -4]]
  
Друга Матриця: 
[[ 4  1 -1]
 [ 1  3 -5]
 [-4  5 -5]]
  
Добуток Матриць: 
[[ 0 -5  3]
 [ 2  6  0]
 [ 8 20 20]]


In [70]:
#14. Створіть матрицю розміром 6x6, заповніть її випадковими цілими числами в діапазоні
#від -50 до 50 та знайдіть суму елементів матриці.


mass16 = np.random.randint(-50, 51, size=(6, 6))
print("Перша Матриця: ")
print(mass16)
print ("  ")
print("Сума елементів в матриці: ", np.sum(mass16))

Перша Матриця: 
[[ 27 -35  43 -50  -1   5]
 [ 21 -34  29 -17  -3  47]
 [ 42 -16  -7 -10   5  26]
 [ 11  -1 -48  13 -22 -28]
 [ 43 -24  36  28  -6 -12]
 [-37 -19  20 -44 -10 -24]]
  
Сума елементів в матриці:  -52


In [72]:
#15. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні
#від 0 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів кожного рядка матриці.

mass16 = np.random.randint(0, 2, size=(4, 4))
print("Перша Матриця: ")
print(mass16)
print ("  ")
print("Добуток елементів: ", mass.prod())

Перша Матриця: 
[[0 1 1 0]
 [1 1 0 1]
 [1 0 0 0]
 [1 1 0 0]]
  
Добуток елементів:  0


In [ ]:
#Висновок: протягом цієї лабораторної робити ми навчились працювати з пакетом NumPy,
#з його основними методами створення масивів, індексації, розглянули основні типи даних NumPy,
#провели арифметичні операції та навіть попрацювали з лінійною алгеброю, що дало нам необхідні
#знання для розв'язання заданих вище завдань та подальшої роботи з предметом "Машинне навчання"